services:

  app:
    build: ./app-test
    restart: always
    ports:
      - ${WEB_PORT:-80}:80
      - ${SSL_PORT:-443}:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DBUSER}
      WORDPRESS_DB_PASSWORD: ${DBPASS}
      WORDPRESS_DB_NAME: ${DBNAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_CACHE_KEY_SALT', '${CACHE_KEY_SALT}');
        define('WP_CACHE', true);
    volumes:
      - wordpress:/var/www/html
      - wp-content:/var/www/html/wp-content

  db:
    image: mariadb:11.1
    restart: always
    environment:
      MARIADB_DATABASE: ${DBNAME}
      MARIADB_USER: ${DBUSER}
      MARIADB_PASSWORD: ${DBPASS}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:6.2
    restart: always
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PMA_PORT:-11080}:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

#  prometheus:
#    build: ./prometheus
#    restart: always
#    ports:
#      - ${PROM_PORT:-9090}:9090
#
volumes:
  wordpress:
  wp-content:
  db:
